# prometheus/prometheus.yml
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'product_service'
    metrics_path: /metrics
    static_configs:
      - targets: ['product_service:50051']

  - job_name: 'cart_service'
    metrics_path: /metrics
    static_configs:
      - targets: ['cart_service:8000']

  - job_name: 'user_service'
    metrics_path: /metrics
    static_configs:
      - targets: ['user_service:9092']

  - job_name: 'order_service'
    metrics_path: /metrics
    static_configs:
      - targets: ['order_service:9092']

